name: Ubuntu 18.04

on:
  push:
    tags:
      - "*"

jobs:
  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          build_folder="build/debug"
          xfg_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          xfg_ver_folder=$(echo $xfg_ver | sed 's/\.//g')
          release_name=fuego-cli-ubuntu-1804-v"$xfg_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../..
          make -j2
          mkdir -p "$release_name/$xfg_ver_folder"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          cp "${exeFiles[@]}" "$release_name/$xfg_ver_folder"
          cd "$release_name"
          tar -czf "$release_name".tar.gz "$xfg_ver_folder"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name/$release_name.tar.gz"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=xfg_ver::${xfg_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fango CLI Suite v${{ steps.build.outputs.xfg_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
